### ISSUE TITLE
how to custom a dataset?

### ISSUE THREAD

**Issue by MasterFlyNight** [Tudyx/ai-dataloader#6]
I was wondering how to build a DataLoader-usable dataset consisting of multiple tch::Tensor, and the error I encountered was not implementing Collate< (Tensor), (Tensor), (Tensor), (Tensor) > for DefaultCollate

**Comment by Tudyx** [comment]
For using Tensor you must activate the `torch` feature and use `ai_dataloader::collate::TorchCollate` instead of `DefaultCollate`.

```sh
ai-dataloader = { version = "0.4.0", features = ["torch"] }
```

The [image example](https://github.com/Tudyx/ai-dataloader/blob/main/examples/image.rs#L90) might help you.

**Comment by FlyAtNight-cup** [comment]
> 

Thank you.
