### ISSUE TITLE
tch dependency is out of date

### ISSUE THREAD

**Issue by kendfrey** [Tudyx/ai-dataloader#79]
The current release 0.6.1 targets tch 0.12.0. The project has been updated to tch 0.16.0, but this has not been published yet. I would love to have an up-to-date release of the crate.

**Comment by Tudyx** [comment]
I would be happy to accept a PR

**Comment by kendfrey** [comment]
This doesn't require a code change, it requires publishing a new release of the crate.

**Comment by Tudyx** [comment]
I've published a new version (0.6.2) than contains the desired changes
